users:
  - user:
      name: '张三'
      openid: 'oO-a2t6Z_awwxOby5Y9eO5VL9Rqg'
      mail: 'aaaa@qq.com'
  - user:
      name: '麻包忠'
      openid: 'oO-a2t4DbCFLkKa1dxpyzEL0X4Uc'
      mail: '2430433989@qq.com'


